kind: pipeline
type: docker
name: build-and-deploy

platform:
  os: linux
  arch: arm64

steps:

  - name: build
    image: node:alpine
    commands:
    - npm install -g pnpm
    - pnpm install
    - pnpm run docs:build
    - tar -czf src/.vuepress/dist.tar.gz src/.vuepress/dist

  - name: deploy
    image: appleboy/drone-scp
    when:
      status:
        - success
    settings:
      host:
        - git.philogag.com
      username: 
        from_secret: deploy_ssh_username
      password:
        from_secret: deploy_ssh_password
      source: src/.vuepress/dist/*
      target: ~/workspace/service/my-blog-site/html
      strip_components: 3
